### ISSUE TITLE
Package doesn't create the dataset that it writes to

### ISSUE THREAD

**Issue by trevorfox** [Liscor/dataform-ga4-tests#1]
This package is a great idea, but it requires prep outside the package. It would be great if the package created the dataset it writes to.

**Comment by trevorfox** [comment]
Added a proposed fix here: https://github.com/Liscor/dataform-ga4-tests/pull/3

**Comment by Liscor** [comment]
Hi Trevor,
thanks for helping out. I think the schema/dataset is created automatically when running the Dataform even though you get an error message like this:
![image](https://github.com/Liscor/dataform-ga4-tests/assets/28501835/b0406fc0-71e9-4d52-b2f5-0633dc84bed4)

 I just tried it, with running it in a fresh project with "All Actions" and it worked and created the Dataset automatically. 
How did you test it, maybe I'm missing something.
Regards
Moritz

**Comment by trevorfox** [comment]
Now, I'm not sure why it didn't create the schema the first time. I just did as you described and deleted the `ga4_testing` schema and reran it. It worked fine. I also looked in the code and found where Dataform implicitly creates referenced schemas. It's there... https://github.com/dataform-co/dataform/blob/2ce51b485998b0567b2a21dc803a2e80665d580b/api/commands/run.ts#L214

Closing #3 :)
